hw_interface_plugin: "mrs_uav_px4_api/Api"

outputs:
  distance_sensor:      true
  gnss:                 true
  gnss_status:          true
  rtk:                  true
  imu:                  true
  altitude:             true
  magnetometer_heading: true
  magnetic_field:       true
  rc_channels:          true
  battery_state:        true
  position:             true
  orientation:          true
  velocity:             true
  angular_velocity:     true
  odometry:             true
  ground_truth:         true